resolver: lts-16.12
packages:
- foo-bar-tui

extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

- github: NorfairKing/safe-coloured-text
  commit: d840dd7b0f13f4d0fd693c1dd93be33f9ee94605
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo

- github: NorfairKing/yamlparse-applicative
  commit: 1d381a4cbc9736a2defc916a93cfcf8000ee7e37
  subdirs:
  - yamlparse-applicative

nix:
  shell-file: shell.nix
