name:                foobar-tui
version:             0.0.0.0
license:             AllRightsReserved

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - brick
  - vty
  - directory
  - cursor

executables:
  foobar-tui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - foobar-tui
