name:                foo-bar-tui
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
  - async
  - autodocodec
  - autodocodec-yaml
  - brick
  - cursor
  - directory
  - envparse
  - mtl
  - optparse-applicative
  - path
  - path-io
  - text
  - vty
  - yaml

executables:
  foo-bar-tui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - foo-bar-tui
